##
## Copyright 2023 Ocean Protocol Foundation
## SPDX-License-Identifier: Apache-2.0
##
services:
  ocean-provider:
    build: .
    ports:
      - 8030:8030
    volumes:
      - ${ARTIFACTS_FOLDER}:/usr/local/:ro
